name: docs

on:
  push:
    branches: [main]
    paths:
      - 'assets/mkdocs/**'
      - 'mkdocs.yml'

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - name: Install MkDocs
        run: pip install mkdocs mkdocs-material

      - name: Build documentation
        run: mkdocs build --config-file mkdocs.yml

      - name: Commit and push docs
        uses: EndBug/add-and-commit@v9
        with:
          add: 'docs'
          message: 'docs: rebuild documentation site'
          default_author: github_actions
